name: Publish with docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEB_APP_NAME: testtimeapiwithdocker
  DOCKER_IMAGE_NAME: ducware/dotnet-test
  DOCKER_IMAGE_TAG: latest

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./DeployAzureExample/Dockerfile
          push: true
          tags: nhannhan/blazordemo:latest


